import { TProduct } from '@/modules/product-builder/types/builder';

export const MOCK_PRODUCTS: TProduct[] = [
  {
    id: 101,
    name: 'Смартфон Vision X-200 Pro',
    type: 'Электроника',
    description_short: 'Флагман с камерой 200 Мп и OLED экраном.',
    description_long:
      'Vision X-200 Pro задает новые стандарты мобильной фотографии. Оснащен процессором нового поколения, 12 ГБ оперативной памяти и аккумулятором на 5000 мАч. Поддерживает сверхбыструю зарядку 120 Вт.',
    code: 'VX-200-PRO-BLK',
    unit: 1,
    category: 4002,
    cashback_type: 'premium_lcard',
    seo_title: 'Купить смартфон Vision X-200 Pro 256GB Black',
    seo_description:
      'Закажите Vision X-200 Pro с бесплатной доставкой и официальной гарантией.',
    seo_keywords: ['смартфон', 'vision', 'x-200', 'флагман', 'камера 200мп'],
    global_category_id: 15,
    marketplace_price: 89990,
    chatting_percent: 3,
    address: 'Москва, ул. Тверская, д. 7, центральный склад',
    latitude: 55.7576,
    longitude: 37.6115,
    photos: [],
    manufacturer: 'Vision Tech Corp',
    cashback_value: 2700,
    external_id: 998877,
    tags: ['новинка', 'хит', 'apple-killer'],
    production_time_min_from: '1',
    production_time_min_to: '3',
    unit_name: 'шт',
    barcodes: ['4607051234567', '4607051234568'],
    prices: [89990, 85000, 92000],
    balances: [15, 42, 0],
    attributes: ['Цвет: Черный', 'Память: 256ГБ', 'RAM: 12ГБ'],
    group_id: [1, 2],
    group_name: 'Vision X Series',
    is_main: true,
    qr_hash: 'a1b2c3d4e5f6',
    qr_url: 'https://api.qrserver.com',
    updated_at: 1708684800,
    created_at: 1708600000,
  },
  {
    id: 202,
    name: 'Кофемашина Barista Home S3',
    type: 'Бытовая техника',
    description_short: 'Автоматическая кофемашина с капучинатором.',
    description_long:
      'Готовьте любимый эспрессо, капучино или латте одним нажатием. Давление 19 бар, керамические жернова и интуитивный сенсорный дисплей.',
    code: 'BH-S3-SILVER',
    unit: 116,
    category: 2477,
    cashback_type: 'standard',
    seo_title: 'Кофемашина Barista Home S3 - характеристики и отзывы',
    seo_description:
      'Профессиональный кофе у вас дома. Кофемашина Barista Home S3 с гарантией от производителя.',
    seo_keywords: ['кофемашина', 'кофе', 'бариста', 'капучино'],
    global_category_id: 127,
    marketplace_price: 45000,
    chatting_percent: 5,
    address: 'Казань, ул. Зайцева, д. 8, Ново-Татарская слобода',
    latitude: 55.7711,
    longitude: 49.1021,
    photos: [],
    manufacturer: 'Home Appliances Ltd',
    cashback_value: 2250,
    external_id: 554433,
    tags: ['кухня', 'дом', 'уют'],
    production_time_min_from: '2',
    production_time_min_to: '5',
    unit_name: 'комплект',
    barcodes: ['4607051999888'],
    prices: [45000, 43500],
    balances: [5, 8],
    attributes: ['Давление: 19 бар', 'Материал: Сталь'],
    group_id: [10],
    group_name: 'Barista Line',
    is_main: false,
    qr_hash: 'z9y8x7w6',
    qr_url: 'https://api.qrserver.com',
    updated_at: 1708690000,
    created_at: 1708500000,
  },
  {
    id: 303,
    name: 'Вешалка Minimalist Iron',
    type: 'Мебель',
    description_short: 'Стильная металлическая вешалка в стиле лофт.',
    description_long:
      'Прочная вешалка из авиационного алюминия. Выдерживает до 50 кг одежды. Легкая сборка за 5 минут без инструментов.',
    code: 'MI-HANGER-BLK',
    unit: 1,
    category: 3310,
    cashback_type: 'lcard_cashback',
    seo_title: 'Напольная вешалка Minimalist Iron купить в СПб',
    seo_description:
      'Идеальное решение для хранения вещей. Черная матовая вешалка Minimalist Iron.',
    seo_keywords: ['вешалка', 'лофт', 'хранение', 'мебель'],
    global_category_id: 12,
    marketplace_price: 3200,
    chatting_percent: 10,
    address: "Санкт-Петербург, склад 'Север', Парнас",
    latitude: 60.0652,
    longitude: 30.3478,
    photos: [],
    manufacturer: 'Iron Design Co',
    cashback_value: 320,
    external_id: 112233,
    tags: ['интерьер', 'акция'],
    production_time_min_from: '1',
    production_time_min_to: '2',
    unit_name: 'шт',
    barcodes: ['4607051112233'],
    prices: [3200],
    balances: [120],
    attributes: ['Высота: 170см', 'Материал: Металл'],
    group_id: null,
    group_name: null,
    is_main: true,
    qr_hash: 'q1r2c3o4',
    qr_url: 'https://api.qrserver.com',
    updated_at: 1708700000,
    created_at: 1708600000,
  },
  {
    id: 1001,
    name: 'Apple iPhone 15 Pro Max 256GB Natural Titanium',
    type: 'Смартфоны',
    description_short: 'Флагман из титана с чипом A17 Pro и кнопкой Action.',
    description_long:
      'Первый iPhone, выполненный из авиационного титана. Невероятно легкий и прочный. Камера 48 Мп с 5-кратным оптическим зумом. Самая высокая производительность в мобильных играх благодаря трассировке лучей.',
    code: 'IPH-15PM-256-NT',
    unit: 1,
    category: 4001,
    cashback_type: 'premium_lcard',
    seo_title: 'Купить iPhone 15 Pro Max 256GB Natural Titanium в Москве',
    seo_description:
      'Новый iPhone 15 Pro Max из титана. Официальная гарантия, лучшая цена и рассрочка.',
    seo_keywords: ['iphone 15 pro max', 'apple', 'титановый айфон', 'смартфон'],
    global_category_id: 15,
    marketplace_price: 135990,
    chatting_percent: 2,
    address: 'Москва, ул. Петровка, д. 2, ЦУМ',
    latitude: 55.7602,
    longitude: 37.6186,
    photos: [],
    manufacturer: 'Apple Inc.',
    cashback_value: 2719,
    external_id: 150001,
    tags: ['pre-order', 'apple', 'flagship'],
    production_time_min_from: '1',
    production_time_min_to: '2',
    unit_name: 'шт',
    barcodes: ['195949048456'],
    attributes: ['Материал: Титан', 'Экран: 6.7 OLED', 'Цвет: Титан'],
    is_main: true,
    updated_at: 1708780000,
    created_at: 1708700000,
  },
  {
    id: 1002,
    name: 'Sony PlayStation 5 Slim (Disc Edition)',
    type: 'Игровые консоли',
    description_short: 'Обновленная тонкая версия самой популярной консоли.',
    description_long:
      'Испытайте молниеносную загрузку благодаря сверхскоростному накопителю SSD. Поддержка тактильной отдачи и адаптивных триггеров DualSense. Потрясающая графика 4K.',
    code: 'PS5-SLIM-DISC',
    unit: 1,
    category: 4005,
    cashback_type: 'lcard_cashback',
    seo_title: 'Игровая приставка Sony PlayStation 5 Slim купить с доставкой',
    seo_description:
      'PlayStation 5 Slim с дисководом. Лучшая цена, гарантия и огромный выбор игр.',
    seo_keywords: ['ps5 slim', 'playstation 5', 'игровая консоль', 'sony'],
    global_category_id: 16,
    marketplace_price: 54990,
    chatting_percent: 5,
    address: 'Санкт-Петербург, Лиговский пр., 30, ТРЦ Галерея',
    latitude: 59.9274,
    longitude: 30.3592,
    photos: [],
    manufacturer: 'Sony Interactive Entertainment',
    cashback_value: 2750,
    external_id: 150002,
    tags: ['gaming', 'sony', 'bestseller'],
    production_time_min_from: '1',
    production_time_min_to: '3',
    unit_name: 'шт',
    barcodes: ['0711719577248'],
    attributes: ['Память: 1ТБ SSD', 'Привод: Есть', 'Цвет: Белый'],
    is_main: true,
    updated_at: 1708781000,
    created_at: 1708701000,
  },
  {
    id: 1003,
    name: 'Dyson Airwrap Multi-styler Complete Long',
    type: 'Уход за волосами',
    description_short: 'Стайлер для разных типов волос с эффектом Коанда.',
    description_long:
      'Единственный стайлер, который завивает, придает форму и скрывает пушащиеся волосы с помощью воздуха, а не экстремального тепла. В комплекте насадки для длинных волос.',
    code: 'DYSON-AW-BLUE',
    unit: 1,
    category: 5002,
    cashback_type: 'premium_lcard',
    seo_title: 'Стайлер Dyson Airwrap Complete Long купить в наличии',
    seo_description:
      'Оригинальный Дайсон Эйрврап для длинных волос. Гарантия и проверка по серийному номеру.',
    seo_keywords: [
      'dyson airwrap',
      'стайлер дайсон',
      'уход за волосами',
      'подарок',
    ],
    global_category_id: 20,
    marketplace_price: 62500,
    chatting_percent: 4,
    address: 'Екатеринбург, ул. 8 Марта, д. 46, ТРЦ Гринвич',
    latitude: 56.8297,
    longitude: 60.5998,
    photos: [],
    manufacturer: 'Dyson Ltd',
    cashback_value: 2500,
    external_id: 150003,
    tags: ['beauty', 'luxury', 'gift'],
    production_time_min_from: '1',
    production_time_min_to: '1',
    unit_name: 'шт',
    barcodes: ['5025155067246'],
    attributes: ['Мощность: 1300Вт', 'Цвет: Синий/Медь'],
    is_main: true,
    updated_at: 1708782000,
    created_at: 1708702000,
  },
  {
    id: 1004,
    name: "Nike Air Jordan 1 Retro High OG 'Chicago'",
    type: 'Обувь',
    description_short: 'Легендарные кроссовки в культовой расцветке.',
    description_long:
      'Возвращение легенды 1985 года. Выполнены из премиальной кожи. Подошва с технологией Air обеспечивает отличную амортизацию и комфорт при ходьбе.',
    code: 'NIKE-AJ1-CHI',
    unit: 116,
    category: 3001,
    cashback_type: 'standard',
    seo_title: 'Кроссовки Nike Air Jordan 1 Chicago - оригинал',
    seo_description:
      'Лимитированная серия Air Jordan 1 Chicago. Только оригинальная продукция с проверкой.',
    seo_keywords: ['nike air jordan', 'chicago', 'кроссовки', 'streetwear'],
    global_category_id: 5,
    marketplace_price: 42000,
    chatting_percent: 15,
    address: 'Москва, Кузнецкий Мост, 14',
    latitude: 55.7618,
    longitude: 37.6223,
    photos: [],
    manufacturer: 'Nike Inc.',
    cashback_value: 4200,
    external_id: 150004,
    tags: ['fashion', 'sneakers', 'limited'],
    production_time_min_from: '2',
    production_time_min_to: '4',
    unit_name: 'пара',
    barcodes: ['00885176140731'],
    attributes: ['Размер: 42 EU', 'Материал: Кожа'],
    is_main: true,
    updated_at: 1708783000,
    created_at: 1708703000,
  },
  {
    id: 1005,
    name: 'LEGO Star Wars Millennium Falcon (Collector Series)',
    type: 'Игрушки',
    description_short:
      'Самая большая и детализированная модель Сокола Тысячелетия.',
    description_long:
      '7541 деталь. Набор включает минифигурки Хана Соло, Чубакки, принцессы Леи и C-3PO. Станет жемчужиной любой коллекции LEGO.',
    code: 'LEGO-SW-75192',
    unit: 1,
    category: 6001,
    cashback_type: 'lcard_cashback',
    seo_title: 'Конструктор LEGO Star Wars Сокол Тысячелетия 75192',
    seo_description:
      'Коллекционный набор Лего Звездные Войны. Огромный размер и потрясающая детализация.',
    seo_keywords: [
      'lego star wars',
      'сокол тысячелетия',
      'лего 75192',
      'конструктор',
    ],
    global_category_id: 10,
    marketplace_price: 84900,
    chatting_percent: 5,
    address: 'Казань, пр. Ибрагимова, 56, ТРК Тандем',
    latitude: 55.8239,
    longitude: 49.0963,
    photos: [],
    manufacturer: 'The LEGO Group',
    cashback_value: 4245,
    external_id: 150005,
    tags: ['hobby', 'star-wars', 'collection'],
    production_time_min_from: '1',
    production_time_min_to: '3',
    unit_name: 'комплект',
    barcodes: ['5702015869324'],
    attributes: ['Деталей: 7541', 'Возраст: 16+'],
    is_main: true,
    updated_at: 1708784000,
    created_at: 1708704000,
  },
  {
    id: 1006,
    name: 'Stanley Quencher H2.0 FlowState Tumbler 1.2L',
    type: 'Посуда',
    description_short: 'Тот самый вирусный термостакан из соцсетей.',
    description_long:
      'Держит холод до 48 часов благодаря вакуумной изоляции. Удобная ручка и узкое дно, которое помещается в подстаканник авто.',
    code: 'STANLEY-Q-40-CRM',
    unit: 1,
    category: 7001,
    cashback_type: 'standard',
    seo_title: 'Термокружка Stanley Quencher 1.2 литра купить',
    seo_description:
      'Оригинальный Стэнли Квенчер. Сохраняет напитки холодными весь день.',
    seo_keywords: [
      'stanley quencher',
      'термокружка',
      'стакан для воды',
      'lifestyle',
    ],
    global_category_id: 25,
    marketplace_price: 6800,
    chatting_percent: 8,
    address: 'Новосибирск, ул. Военная, 5, ТРЦ Аура',
    latitude: 55.0263,
    longitude: 82.9372,
    photos: [],
    manufacturer: 'Stanley-PMI',
    cashback_value: 544,
    external_id: 150006,
    tags: ['trending', 'sport', 'eco'],
    production_time_min_from: '1',
    production_time_min_to: '2',
    unit_name: 'шт',
    barcodes: ['082442964121'],
    attributes: ['Объем: 1.2л', 'Цвет: Крем'],
    is_main: true,
    updated_at: 1708785000,
    created_at: 1708705000,
  },
  {
    id: 1007,
    name: "Samsung Odyssey G9 OLED 49' UltraWide",
    type: 'Мониторы',
    description_short: 'Изогнутый игровой монитор с эффектом погружения.',
    description_long:
      'Разрешение Dual QHD, частота обновления 240 Гц и время отклика 0.03 мс. Идеально для симрейсинга и профессионального монтажа.',
    code: 'SAMSUNG-G9-OLED',
    unit: 1,
    category: 4004,
    cashback_type: 'premium_lcard',
    seo_title: 'Монитор Samsung Odyssey G9 OLED купить в Москве',
    seo_description:
      '49 дюймов чистого удовольствия. Samsung G9 OLED — лучший выбор для геймера.',
    seo_keywords: [
      'samsung odyssey g9',
      'oled монитор',
      'игровой монитор',
      '49 дюймов',
    ],
    global_category_id: 15,
    marketplace_price: 189000,
    chatting_percent: 3,
    address: 'Москва, ул. Садовая-Спасская, д. 3, корп. 1',
    latitude: 55.7712,
    longitude: 37.6432,
    photos: [],
    manufacturer: 'Samsung Electronics',
    cashback_value: 9450,
    external_id: 150007,
    tags: ['setup', 'gaming', 'workstation'],
    production_time_min_from: '2',
    production_time_min_to: '5',
    unit_name: 'шт',
    barcodes: ['8806094777541'],
    attributes: ['Экран: 49 OLED', 'Частота: 240Гц'],
    is_main: true,
    updated_at: 1708786000,
    created_at: 1708706000,
  },
  {
    id: 1008,
    name: 'Kindle Paperwhite 16GB (11th Gen)',
    type: 'Электронные книги',
    description_short: 'Лучшая читалка с регулируемой теплотой подсветки.',
    description_long:
      'Экран 6.8 дюйма без бликов. Водонепроницаемость IPX8. Одной зарядки хватает на 10 недель чтения.',
    code: 'AMZ-KINDLE-PW11',
    unit: 1,
    category: 4008,
    cashback_type: 'standard',
    seo_title: 'Электронная книга Amazon Kindle Paperwhite 2023 купить',
    seo_description:
      'Новый Kindle Paperwhite с USB-C. Самый комфортный экран для чтения книг.',
    seo_keywords: ['kindle', 'электронная книга', 'amazon kindle', 'читалка'],
    global_category_id: 15,
    marketplace_price: 17500,
    chatting_percent: 5,
    address: 'Москва, Багратионовский проезд, 7, Горбушкин Двор',
    latitude: 55.7416,
    longitude: 37.4984,
    photos: [],
    manufacturer: 'Amazon Labs',
    cashback_value: 875,
    external_id: 150008,
    tags: ['reading', 'travel', 'amazon'],
    production_time_min_from: '1',
    production_time_min_to: '2',
    unit_name: 'шт',
    barcodes: ['840080536415'],
    attributes: ['Память: 16ГБ', 'Экран: E-Ink 6.8'],
    is_main: true,
    updated_at: 1708787000,
    created_at: 1708707000,
  },
  {
    id: 1009,
    name: 'Marshall Emberton II Black & Brass',
    type: 'Акустика',
    description_short:
      'Компактная колонка с узнаваемым рок-н-ролльным дизайном.',
    description_long:
      'Более 30 часов портативного воспроизведения. Технология True Stereophonic для объемного звука 360°. Пыле- и водонепроницаемость IP67.',
    code: 'MARSHALL-EMB-2',
    unit: 1,
    category: 4006,
    cashback_type: 'lcard_cashback',
    seo_title: 'Портативная колонка Marshall Emberton II оригинал',
    seo_description:
      'Легендарный звук Маршалл в твоем кармане. Emberton II — стиль и мощь.',
    seo_keywords: [
      'marshall',
      'emberton',
      'портативная колонка',
      'bluetooth speaker',
    ],
    global_category_id: 16,
    marketplace_price: 19900,
    chatting_percent: 6,
    address: 'Краснодар, ул. им. Володи Головатого, 313, ТРЦ Галерея',
    latitude: 45.0384,
    longitude: 38.9733,
    photos: [],
    manufacturer: 'Zound Industries',
    cashback_value: 1194,
    external_id: 150009,
    tags: ['music', 'marshall', 'style'],
    production_time_min_from: '1',
    production_time_min_to: '2',
    unit_name: 'шт',
    barcodes: ['7340055385558'],
    attributes: ['Время работы: 30ч+', 'Цвет: Black/Brass'],
    is_main: true,
    updated_at: 1708788000,
    created_at: 1708708000,
  },
  {
    id: 1010,
    name: 'KitchenAid Artisan 4.8L Stand Mixer',
    type: 'Кухонная техника',
    description_short: 'Культовый планетарный миксер для выпечки.',
    description_long:
      'Профессиональная надежность и цельнометаллический корпус. 10 скоростей и более 15 доступных насадок для приготовления чего угодно: от пасты до мороженого.',
    code: 'KA-ART-4.8-RED',
    unit: 1,
    category: 2478,
    cashback_type: 'premium_lcard',
    seo_title: 'Миксер KitchenAid Artisan 4.8л красный купить',
    seo_description:
      'Мечта каждого кондитера. Оригинальный миксер KitchenAid с доставкой.',
    seo_keywords: [
      'kitchenaid artisan',
      'миксер',
      'планетарный миксер',
      'выпечка',
    ],
    global_category_id: 127,
    marketplace_price: 64900,
    chatting_percent: 4,
    address: 'Ростов-на-Дону, пр. Михаила Нагибина, 32/2, ТРК Горизонт',
    latitude: 47.2581,
    longitude: 39.7189,
    photos: [],
    manufacturer: 'Whirlpool Corporation',
    cashback_value: 2596,
    external_id: 150010,
    tags: ['kitchen', 'chef', 'premium'],
    production_time_min_from: '2',
    production_time_min_to: '4',
    unit_name: 'шт',
    barcodes: ['5413184200465'],
    attributes: ['Объем чаши: 4.8л', 'Цвет: Empire Red'],
    is_main: true,
    updated_at: 1708789000,
    created_at: 1708709000,
  },
];
